#!/usr/bin/env bash

chsh -s /bin/zsh

echo "Installing oh-my-zsh"
source "./scripts/install_oh_my_zsh.sh"

echo "Installing zsh syntax highlighting"
git clone --depth 1 git@github.com:zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

echo "Installing homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Symlinking dotfiles"
ln -sf ~/.dotfiles/rubygems/gemrc ~/.gemrc
ln -sf ~/.dotfiles/git/gitconfig ~/.gitconfig
ln -sf ~/.dotfiles/git/gitignore ~/.gitignore
ln -sf ~/.dotfiles/rspec/rspec ~/.rspec
ln -sf ~/.dotfiles/zsh/zshrc ~/.zshrc
ln -sf ~/.dotfiles/tmux/tmux.conf ~/.tmux.conf

echo "Setting up development directories"
mkdir -p ~/Projects/{misc,personal,work}
mkdir -p ~/go/{bin,pkg,src}

echo "Installing brew bundle"
brew bundle

echo "Clean up the brewing"
brew cleanup
rm -rf $(brew --cache)

echo "Install ITerm2 colour preset"
mkdir -p ~/Projects/misc/base16-iterm2
wget https://raw.githubusercontent.com/chriskempson/base16-iterm2/master/base16-colors.dark.256.itermcolors -P ~/Projects/misc/base16-iterm2
