ZSH=$HOME/.oh-my-zsh

zsh_home_config="$HOME/.dotfiles/zsh"

ZSH_THEME="robbyrussell"

plugins=(autojump docker docker-compose history-substring-search zsh-syntax-highlighting zsh-autosuggestions golang tmux)

source $ZSH/oh-my-zsh.sh

#set editor
export EDITOR="code --wait"

export GOPATH=~/go
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
export PATH="$PATH:$GOPATH/bin"

# Brew shell initialize
eval "$(/opt/homebrew/bin/brew shellenv)"

# Set KUBECONFIG
export KUBECONFIG="$HOME/.kube/config"

# Set language encodings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Allow the GPG-agent to access the terminal for passphrase input
export GPG_TTY=$(tty)

# Source private file specific to each workstation
[[ -f "$HOME/.zsh_private" ]] && source "$HOME/.zsh_private"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

#Autojump
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

# Store and load aliases
[[ -f "$zsh_home_config/aliases" ]] && source "$zsh_home_config/aliases"

# Loads Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Loads Command-line fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
autoload -U +X bashcompinit && bashcompinit

# Load rbenv
eval "$(rbenv init -)"

# Kubernetes prompt
source "/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1

export POWERLINE_CONFIG_COMMAND=$(which powerline-config)
