ZSH=$HOME/.oh-my-zsh

zsh_home_config="$HOME/.dotfiles/zsh"

ZSH_THEME="robbyrussell"

plugins=(autojump bundler docker docker-compose gem history-substring-search ruby zsh-syntax-highlighting go)

source $ZSH/oh-my-zsh.sh

#set editor
export EDITOR="subl -n -w"

export GOPATH=~/go
export GOROOT=/usr/local/opt/go/libexec
export PATH="${HOME}/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
export PATH="/usr/local/opt/postgresql@9.4/bin:$PATH"

# Set language encodings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#rbenv init
eval "$(rbenv init -)"

#Autojump
[[ -f $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Store and load aliases
[[ -f "$zsh_home_config/aliases" ]] && source "$zsh_home_config/aliases"

# Loads Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Loads Command-line fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Sets kubectl current context rprompt
autoload -U colors; colors
source /usr/local/etc/zsh-kubectl-prompt/kubectl.zsh
RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/vault vault
